services:
  server:
    build: ./backend
    restart: always
    container_name: server
    ports:
      - 8080:8080
    volumes:
      - ./public:/quizorb/backend/public
    environment:
      - ENVIRONMENT=production
  nginx:
    build: ./
    ports:
      - 80:80
    restart: always
    container_name: ngx
    depends_on:
      - server