services:
  server:
    build: ./backend
    restart: always
    container_name: server
    ports:
      - 8080:8080
    volumes:
      - ./backend:/quizorb/backend
    environment:
      - ENVIRONMENT=production