package entity

type Question struct {
	ID          uint   `json:"id"`
	Question    string `json:"question"`
	IMGQuestion string `json:"url_answer"`
	Theme       uint
	Costs       int
	Status      string
}

func SetQuestions() []Question {
	return []Question{
		{ID: 1, Theme: 1, Costs: 100, Question: "Пассажир первого поезда «Самара-Оренбург».Один из величайших писателей мировой литературы.", IMGQuestion: "https://xn----7sbbaazuatxpyidedi7gqh.xn--p1ai/i/trans/parovoz/28.jpg"},
		{ID: 2, Theme: 1, Costs: 200, Question: "«Отец» Штирлица. Работал в Оренбуржье над биографией лидера белого казачества атамана Александра Дутова.", IMGQuestion: "https://cdn.iz.ru/sites/default/files/styles/1920x1080/public/article-2018-10/RIAN_2409537.HR_.ru_.jpg?itok=ftIhTNFz"},
		{ID: 3, Theme: 1, Costs: 300, Question: "По итогу визита в Оренбург и Бердскую слободу местные жители сделали вывод – приезжал антихрест. Особенно оренбуржцев поразила темная кожа и длинные ногти гостя.", IMGQuestion: "https://news.store.rambler.ru/img/63cdade2336b8087642677fdaadb9768?img-1-resize=width%3A1280%2Cheight%3A960%2Cfit%3Acover&img-format=auto"},
		{ID: 4, Theme: 1, Costs: 400, Question: "Массаракш — распространённое ругательство, употребляемое жителями вымышленной планеты Саракш, дословно обозначающее «Мир наизнанку». Название «Саракш» было	образовано от названия посёлка Саракташ	Оренбургской области, аналогично другому фантастическому топониму в творчестве братьев — названию фигурирующего в романе «Отягощённые злом, или Сорок лет спустя» города Ташлинск, образованного от наименования села Ташла, также расположенного в Оренбургской области.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPlGxW1-8QC5-Q-MyA91kJZZcaBkIBDhN1Eg&usqp=CAU"},
		{ID: 5, Theme: 1, Costs: 500, Question: "Наставник цесаревича Александра Николаевича, посещал Оренбуржье вместе со своим учеником. Автор	слов государственного гимна Российской империи «Боже, Царя храни!».", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMi4i6jV0wmBG44zJ43o2jhSwWOoFFHKC5jw&usqp=CAU"},
		{ID: 6, Theme: 2, Costs: 100, Question: "С Оренбургским краем был связан с начала своей биографии Его отец армейским офицер, последние годы жизни (1749-1754) служил в Оренбурге, где будущий поэт получил первоначальное образование. \n«Заметил Пушкина» и «в гроб сходя благословил».", IMGQuestion: "https://ic.pics.livejournal.com/viktoriiako/72565754/1294461/1294461_900.png"},
		{ID: 7, Theme: 2, Costs: 200, Question: "Отец русской истории, именно он придал современное толкование термину «промышленность». Родился в Преображенке в Бузулукского уезда.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuzPUZ8Ct1rWiXjozm7kyR0Tf1-QBDNN62IQ&usqp=CAU"},
		{ID: 8, Theme: 2, Costs: 300, Question: "Назовите известного писателя.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7X_wQ0sPUzWyAOvW256mnbkZ2aUllwEztEg&usqp=CAU"},
		{ID: 9, Theme: 2, Costs: 400, Question: "Благодаря ему мы знаем какой бывает «Горячий снег» и том как «Батальоны просят Огня».", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNC2XqnhIBmhVCn4gr51OZ_3obI72RDMxIZQ&usqp=CAU"},
		{ID: 10, Theme: 2, Costs: 500, Question: "Советский палеотолог, писатель-фантаст и социальный мыслитель. Автор романов «Туманность Андромеды», «Таис Афинская» и «Лезвие бритвы». Участвовал в раскопках Карталинского рудгого поля.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkiGG7rbKp9FsmBHxqGnJ3QSSufcShFrVXEA&usqp=CAU"},
		{ID: 11, Theme: 3, Costs: 100, Question: "Актёр Магнитогорский драматический театр имени А. С. Пушкина Оренбургский областной драматический театр	имени М. Горького, а потом и Московский драматический театр на Малой Бронной. \nИменно он попросил Максима Максимовича Исаева остаться после совещания.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTvroe5WmLkpRwmueK02UM0-ebDzZLc16oNw&usqp=CAU"},
		{ID: 12, Theme: 3, Costs: 200, Question: "Жил в Оренбуржье до Большого каретного.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQy3jAFwTP9fawqjpORSjrUwa7dvQs52JnKTw&usqp=CAU"},
		{ID: 13, Theme: 3, Costs: 300, Question: "Французский рестлер, более известным под именем	Французский ангел. Родился на территории оренбургской губернии. Прототипом какого мультипликационного персонажа она стал?", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeUMAxfZ091xon5ba5QS2kR2BMgvS_uI4vfQ&usqp=CAU"},
		{ID: 14, Theme: 3, Costs: 400, Question: "Голос Гарри Поттера и Фродо Беггинса, быший солист группы Revolvers.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSA93NyAvMfBtSJ2EDUCE7iMWQGNoY6a-1kQ&usqp=CAU"},
		{ID: 15, Theme: 3, Costs: 500, Question: "Назовите популярного исполнителя.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN4b4hhNYWHVx6qTw-9ftf0wGp8iDzAM6p6Q&usqp=CAU"},
		{ID: 16, Theme: 4, Costs: 100, Question: "", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGtTiDrBbtecJeL0on2qpufIaCZIPfS9Ikqg&usqp=CAU"},
		{ID: 17, Theme: 4, Costs: 200, Question: "", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf_JUs1s3npadfarQCZ3NQWxDF9JNpt0QJdg&usqp=CAU"},
		{ID: 18, Theme: 4, Costs: 300, Question: "", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVQyPRxwgGnhxUP4ctblsIlwwEeu3g4N-QNA&usqp=CAU"},
		{ID: 19, Theme: 4, Costs: 400, Question: "", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWyROUCbXtAK-sEYr7GCiMOpl-Ql-tSK0pTw&usqp=CAU"},
		{ID: 20, Theme: 4, Costs: 500, Question: "", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShGusi1Xuoi-y3C6ZkXlwsJFpZH9tz2_MBNQ&usqp=CAU"},
		{ID: 21, Theme: 5, Costs: 100, Question: "Император Всероссийский, который по одной из легенд закончил жизнь как старец Федор Кузьмич.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBTHbgOaxLajtK_lnAvGykxw4O_34LubWKw&usqp=CAU"},
		{ID: 22, Theme: 5, Costs: 200, Question: "Освободитель и Вешатель, пережил 7 покушений.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqbMRincO18CRhYuyoNwtYyOynfBBa_A4lLA&usqp=CAU"},
		{ID: 23, Theme: 5, Costs: 300, Question: "", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyfc9hFse88flfy8q4K2Lyh6e1gTcbV3rCKg&usqp=CAU"},
		{ID: 24, Theme: 5, Costs: 400, Question: "Этот Оренбуржец однажды стал руководителем Советского Союза, правда не на долго. В настоящее время его память никак не увековечена в нашем городе, вероятно в связи со спорным характером его наследия. Последние 33 года жизни провёл практически в забвении и отчуждении от политики.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqLw9qmFfSQjBKCzOiPgLtKG3mgCvltXHhHw&usqp=CAU"},
		{ID: 25, Theme: 5, Costs: 500, Question: "Весь мир сейчас идёт наоборот. Назовите автора цитаты.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0FiHnvQLvGOnUNQ6Vg8p_aEYM0IG-GVvoKA&usqp=CAU"},
		{ID: 26, Theme: 6, Costs: 100, Question: "Герой обороны Сталинграда. В американском фильме «Враг у ворот» его роль исполнил известный актёр Джуд Лоу.	Его книга является настольным пособием снайперов армии США. Кто он?", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjng063Yv8_g7w8asF9BiYq6X8n4FZKB6yog&usqp=CAU"},
		{ID: 27, Theme: 6, Costs: 200, Question: "Один из самых знаминитых героев Великой Отечественной войны. Его подвиг был повторён более 400 раз. Наш герой проходил обучение в Краснохолмском пехотном училище. Кто он?", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkZ-rtR2CMMmTDpUNMmvblsqP3z9j9l878lA&usqp=CAU"},
		{ID: 28, Theme: 6, Costs: 300, Question: "Вероятнее всего именно этот человек и доблесть ввереного ему военного соединения остановили нацистов в Сталинграде. Дважды герой Совесткого Союза, уроженец	Шарлыка, кто он?", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-w-mRLXFv8DT0kHh0GJQnxvOIubPGDnx3sw&usqp=CAU"},
		{ID: 29, Theme: 6, Costs: 400, Question: "Советская лётчица, единственная в мире женщина, совершившая воздушный таран, обучалась в Оренбургской военной авиационной школе лётчиков", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE1oZJwh8JPi3FzwtvaR8hrTZkoxqu6kxPaQ&usqp=CAU"},
		{ID: 30, Theme: 6, Costs: 500, Question: "17 марта 2016 года, находившийся неделю в тылу противника, был окружён боевиками «Исламского государства» в районе населённого пункта Тадмор (провинция Хомс, Сирия). Старший лейтенант вступил в бой с террористами и не желая	сдаваться в плен, вызвал авиаудар на себя. Вместе с	геройски погибшим офицером были уничтожены и окружившие его боевики «Исламского государства». Назовите фамилию героя.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9Q4H5df1_vfrDYdQhJvzSraYIXgUIRhx6vw&usqp=CAU"},
		{ID: 31, Theme: 7, Costs: 100, Question: "Вместе с группой «Вымпел» прибыл в город Беслан республики Северная Осетия — Алания, где 1 сентября 2004 года более тридцати террористов под захватили в заложники свыше 1100 детей и взрослых в здании школы № 1.\n\nПосле того, как на третий день в спортзале, где содержались большинство заложников, произошли взрывы, вызвавшие частичное	обрушение крыши и стен спортзала, выжившие люди стали разбегаться. Оперативно-боевая группа, в составе которой был наш герой, получила приказ на штурм здания, так как боевики открыли шквальный огонь по заложникам. Первым проник в помещение столовой, куда боевики перегнали выживших после взрывов в спортзале заложников, и лично	уничтожил одного террориста. Когда другой бандит бросил в скопление людей гранату, спас жизни заложникам, закрыв их от взрыва своим	телом. Уроженец города Орска. Назовите фамилию героя.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDaSfsIfHbfD4tQIQ2C6G-5LKGXt5IGjS9Jw&usqp=CAU"},
		{ID: 32, Theme: 7, Costs: 200, Question: "Русский военный, участник Белого движения, атаман Оренбургского казачества, генерал-лейтенант. Предводитель казацкого восстания на Урале в 1918	году. Участник «Голодного похода». Был ликвидирован	диверсионной группой ВЧК в Китае в 1921 году.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_c95UWGTXsnnS_X6yIkIpVgaBx7oGKUS7Kg&usqp=CAU"},
		{ID: 33, Theme: 7, Costs: 300, Question: "Лётчик и воздухоплаватель, первый в мире летчик-бомбардировщик, первый в Российской Империи военный летчик-инструктор. Окончил Оренбургский	Неплюевский кадетский корпус.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyUc4f87A4Aer9rSPk9qvnppJzjuBDbg5MxA&usqp=CAU"},
		{ID: 34, Theme: 7, Costs: 400, Question: "Одна из самых известных исторических личностей эпохи Гражданской войны в России. Увековечен в книге Дмитрия	Фурманова «Чапаев» и одноимённом фильме братьев	Васильевых, а также в многочисленных анекдотах.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnZC8faJBqtzxNavH-p7qkc_aYNXTPyCa0JA&usqp=CAU"},
		{ID: 35, Theme: 7, Costs: 500, Question: "Оренбургский космонавт. Отец космонавта.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiS0tSGEzoFvqb7JUtpfQuOXsr5wMwB1F-PA&usqp=CAU"},
		{ID: 36, Theme: 8, Costs: 100, Question: "Первый советский космонавт, побывавший в космосе дважды. Первый космонавт, погибший в ходе полёта. Его космический аппарат разбился в Оренбургской области.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEDVgXSEH14rydFPQx-Jvucw8brkYGblnZyA&usqp=CAU"},
		{ID: 37, Theme: 8, Costs: 200, Question: "Назовите фамилию, имя и отчество жены Гагарина в девичестве.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4k24svAcp2nHFjPwi8yUI8vrhjrnSGwd-Pg&usqp=CAU"},
		{ID: 38, Theme: 8, Costs: 300, Question: "Светский учёный-радиотехник и кибернетик, основоположник отечественной школы биологической кибернетики и биотехнических систем и технологий. Родился в Оренбурге, где его семья проживала на улице Советской.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSeC1pwMf4U36c00POZdWYjOMpFoSRHEYJbA&usqp=CAU"},
		{ID: 39, Theme: 8, Costs: 400, Question: "Советский физик, академик Академии наук СССР, один из основателей совесткой атомной школы. Родился и вырос в Оренбурге.", IMGQuestion: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsgiz_-hUvcqq9kqzGm8dj19EVxf8aDOOwbw&usqp=CAU"},
		{ID: 40, Theme: 8, Costs: 500, Question: "Советский и российский физик, академик РАН (2019). Директор Института физики твердого тела РАН (2002—2017),	академик-секретарь Отделения физических наук (с 2022), член ряда комиссий, советов и иных авторитетных органов РАН. Родился и вырос в Оренбурге.", IMGQuestion: "https://media.fulledu.ru/documents/covers/2018.04.13.11/article/100060000000000000002954.jpg"},
		{ID: 41, Theme: 9, Costs: 100, Question: "Последний президент Академии наук СССР, учёный в области вычислительной математики, физики атмосферы, геофизики. Уроженец села Петрохеронец Грачёвского	района Оренбургской губернии.", IMGQuestion: "https://avatars.mds.yandex.net/i?id=53d472ebf46191383d71bf0398163f86-4809466-images-thumbs&n=13"},
		{ID: 42, Theme: 9, Costs: 200, Question: "Кристаллограф, минералог и математик. Академик Российской академии наук, директор петербургского Горного института (1905—1910). Член организации «Земля и Воля». Родился в Оренбурге.", IMGQuestion: "https://avatars.mds.yandex.net/i?id=796e2a441d078495c817f1a9cf083224fb94dd6a-4073135-images-thumbs&n=13"},
		{ID: 43, Theme: 9, Costs: 300, Question: "", IMGQuestion: "https://avatars.mds.yandex.net/i?id=f8dcbdd348dfac8a328b14ab3aa7badac125e135-9461051-images-thumbs&n=13"},
		{ID: 44, Theme: 9, Costs: 400, Question: "Немецкий географ, натуралист и путешественник, один из основателей географии как самостоятельной науки", IMGQuestion: "https://avatars.mds.yandex.net/i?id=45e5dafe791e6315b2d2d2b59426e3bcc285be51-6849173-images-thumbs&n=13"},
		{ID: 45, Theme: 9, Costs: 500, Question: "«Один из наиболее выдающихся естествоиспытателей всех стран и времён…» — так начинается персоналия Ф. П. Кеппена об учёном в «Русском биографическом словаре». «…Природный немец, родом пруссак, <…> отдавший всю жизнь России… отличался <…> широтой своих научных интересов, попытками научного, глубокого творчества в области искания обобщений в наблюдательных науках, <…> колоссальной работоспособностью и точным владением вечными	элементами научного метода…», — сказал В. И.Вернадский", IMGQuestion: "https://avatars.mds.yandex.net/i?id=0a919728eea6a20290119417c492c35c41629d76-9069510-images-thumbs&n=13"},
		{ID: 46, Theme: 10, Costs: 100, Question: "Первый «Заслуженый географ Российской Федерации». Вице-президент Русского географического общества", IMGQuestion: "https://avatars.mds.yandex.net/i?id=e422686e7965b2b8a2389c0123c9c56e-4435835-images-thumbs&n=13"},
	}
}
